#!/bin/bash
# This is Archlinux rc.d script

. /etc/rc.conf
. /etc/rc.d/functions

daemon_name="goanysync"

start() {
  stat_busy "Starting ${daemon_name} daemon"
  if [[ -f /run/daemons/${daemon_name} ]]; then
    stat_die
  else
    /usr/bin/${daemon_name} check
    add_daemon ${daemon_name}
    /usr/bin/${daemon_name} sync
    stat_done
  fi
}

sync() {
  if [[ -f /run/daemons/${daemon_name} ]]; then
    stat_busy "Starting ${daemon_name} daemon"
  else
    stat_busy "Starting to sync"
  fi

  /usr/bin/${daemon_name} sync

  if [[ -f /run/daemons/${daemon_name} ]]; then
    add_daemon ${daemon_name}
  fi
  stat_done
}

stop() {
  stat_busy "Stopping ${daemon_name} daemon"
  if [[ ! -f /run/daemons/${daemon_name} ]]; then
    stat_die  # check if already stopped
  else
    /usr/bin/${daemon_name} sync
    /usr/bin/${daemon_name} unsync
    rm_daemon ${daemon_name}
    stat_done
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  sync)
    sync
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "usage $0 {start|stop|sync}"
esac

exit 0

# vim:set ts=2 sw=2 sts=2 et:
